Merge bitcoin/bitcoin#21864: fix permissions on 00_setup_env_native_fuzz_with_msan.sh
d48565d10968171edeeb75c1a0af8f4119bb99bc fix permissions on 00_setup_env_native_fuzz_with_msan (glozow)

Pull request description:

  I think there was a silent merge conflict between #21852 and #21740?

  I have a [linter failure](https://cirrus-ci.com/task/5436849834426368):

  ```
  File "ci/test/00_setup_env_native_fuzz_with_msan.sh" contains a shebang line, but has the file permission 644 instead of the expected executable permission 755. Do "chmod 755 ci/test/00_setup_env_native_fuzz_with_msan.sh" (or remove the shebang line).
  ERROR: There were 1 failed tests in the lint-files.py lint test. Please resolve the above errors.
  ^---- failure generated from test/lint/lint-files.sh
  ```

ACKs for top commit:
  MarcoFalke:
    ACK d48565d10968171edeeb75c1a0af8f4119bb99bc

Tree-SHA512: 445bdd738faf007451f40bbcf360dd1fb4675e17a4c96546e6818c12e33dd336dadd95cf8d4b5f8df1d6ccfbc4bf5496864bb5528e416cea894857b6b732140c

Co-authored-by: MarcoFalke <falke.marco@gmail.com>